server:
  port: 8002
mybatis:
  type-aliases-package: com.huihui.it.boke.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: boke-it-mysql-db
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db02
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: boke-mysql-db-8002
    prefer-ip-address: true
info:
  app.name: dahui
  photo.name: 13213590636